name 'apache'
maintainer 'Larry Jones'
maintainer_email 'mrwizard82d1@gmail.com'
license 'Apache 2.0'
description 'Installs/Configures apache'
long_description 'Installs/Configures apache'
version '0.1.0'
